use e_commerce;

create table product (
	id INT,
	name VARCHAR(50),
	newPrice INT,
	oldPrice INT,
	origin VARCHAR(14),
	saleOff VARCHAR(50)
);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (1, 'Konklux', 83, 21, 'Huế', 36);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (2, 'Namfix', 43, 95, 'Đã Nẵng', 30);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (3, 'Voltsillam', 59, 32, 'Hà Nội', 20);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (4, 'Rank', 64, 35, 'Tp.Hồ Chí Minh', 55);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (5, 'It', 10, 74, 'Hải Phòng', 11);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (6, 'Tempsoft', 40, 100, 'An Giang', 14);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (7, 'Zamit', 64, 98, 'Cà Mau', 48);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (8, 'Wrapsafe', 48, 9, 'Vũng Tàu', 25);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (9, 'Otcom', 23, 21, 'Đồng Nai', 13);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (10, 'Zathin', 65, 1, 'Huế', 41);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (11, 'Transcof', 88, 6, 'Đã Nẵng', 12);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (12, 'Ronstring', 50, 46, 'Hà Nội', 60);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (13, 'Treeflex', 33, 89, 'Tp.Hồ Chí Minh', 49);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (14, 'Job', 58, 81, 'Hải Phòng', 57);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (15, 'Ronstring', 84, 94, 'An Giang', 45);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (16, 'Lotlux', 97, 17, 'Cà Mau', 30);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (17, 'Opela', 50, 11, 'Vũng Tàu', 28);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (18, 'Sub-Ex', 7, 51, 'Đồng Nai', 38);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (19, 'Andalax', 2, 1, 'Huế', 16);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (20, 'Wrapsafe', 12, 13, 'Đã Nẵng', 57);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (21, 'Bamity', 74, 99, 'Hà Nội', 29);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (22, 'Duobam', 96, 76, 'Tp.Hồ Chí Minh', 19);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (23, 'Fintone', 68, 25, 'Hải Phòng', 15);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (24, 'It', 47, 14, 'An Giang', 56);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (25, 'Bitwolf', 39, 65, 'Cà Mau', 49);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (26, 'Stronghold', 81, 84, 'Vũng Tàu', 56);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (27, 'Tampflex', 22, 47, 'Đồng Nai', 22);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (28, 'Treeflex', 28, 47, 'Huế', 51);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (29, 'Regrant', 89, 79, 'Đã Nẵng', 10);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (30, 'Tampflex', 88, 10, 'Hà Nội', 48);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (31, 'Tampflex', 57, 80, 'Tp.Hồ Chí Minh', 20);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (32, 'Lotlux', 9, 29, 'Hải Phòng', 15);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (33, 'Opela', 55, 37, 'An Giang', 21);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (34, 'Cookley', 52, 30, 'Cà Mau', 48);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (35, 'Aerified', 9, 41, 'Vũng Tàu', 54);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (36, 'Redhold', 90, 5, 'Đồng Nai', 30);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (37, 'Pannier', 94, 83, 'Huế', 32);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (38, 'Bytecard', 31, 79, 'Đã Nẵng', 32);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (39, 'Cookley', 84, 12, 'Hà Nội', 25);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (40, 'Overhold', 24, 85, 'Tp.Hồ Chí Minh', 17);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (41, 'Lotlux', 33, 39, 'Hải Phòng', 31);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (42, 'Hatity', 41, 68, 'An Giang', 13);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (43, 'Bitwolf', 88, 31, 'Cà Mau', 21);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (44, 'Aerified', 1, 9, 'Vũng Tàu', 59);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (45, 'Alpha', 24, 73, 'Đồng Nai', 28);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (46, 'Zaam-Dox', 44, 82, 'Huế', 12);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (47, 'Overhold', 28, 97, 'Đã Nẵng', 32);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (48, 'Konklux', 29, 43, 'Hà Nội', 22);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (49, 'Zoolab', 54, 87, 'Tp.Hồ Chí Minh', 35);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (50, 'Tres-Zap', 56, 32, 'Hải Phòng', 49);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (51, 'Treeflex', 74, 47, 'An Giang', 50);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (52, 'Transcof', 86, 78, 'Cà Mau', 25);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (53, 'Latlux', 64, 53, 'Vũng Tàu', 22);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (54, 'Duobam', 61, 57, 'Đồng Nai', 19);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (55, 'Tres-Zap', 72, 17, 'Huế', 10);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (56, 'Domainer', 86, 61, 'Đã Nẵng', 50);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (57, 'Rank', 11, 64, 'Hà Nội', 21);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (58, 'Bamity', 18, 29, 'Tp.Hồ Chí Minh', 23);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (59, 'Otcom', 56, 4, 'Hải Phòng', 57);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (60, 'Bigtax', 15, 15, 'An Giang', 25);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (61, 'Domainer', 93, 63, 'Cà Mau', 22);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (62, 'Solarbreeze', 11, 16, 'Vũng Tàu', 42);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (63, 'Andalax', 57, 96, 'Đồng Nai', 29);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (64, 'Stronghold', 37, 58, 'Huế', 30);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (65, 'Span', 78, 4, 'Đã Nẵng', 58);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (66, 'Andalax', 20, 34, 'Hà Nội', 19);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (67, 'Ventosanzap', 47, 41, 'Tp.Hồ Chí Minh', 54);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (68, 'Fix San', 10, 26, 'Hải Phòng', 10);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (69, 'Otcom', 41, 36, 'An Giang', 28);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (70, 'Voyatouch', 7, 16, 'Cà Mau', 53);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (71, 'Treeflex', 48, 8, 'Vũng Tàu', 55);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (72, 'Fintone', 22, 82, 'Đồng Nai', 32);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (73, 'Sonair', 21, 17, 'Huế', 23);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (74, 'Rank', 26, 100, 'Đã Nẵng', 34);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (75, 'Kanlam', 14, 35, 'Hà Nội', 39);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (76, 'Y-Solowarm', 47, 84, 'Tp.Hồ Chí Minh', 55);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (77, 'Zontrax', 53, 6, 'Hải Phòng', 46);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (78, 'Tempsoft', 39, 24, 'An Giang', 51);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (79, 'Redhold', 39, 16, 'Cà Mau', 17);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (80, 'Bytecard', 99, 45, 'Vũng Tàu', 26);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (81, 'Greenlam', 82, 61, 'Đồng Nai', 10);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (82, 'Ronstring', 94, 45, 'Huế', 38);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (83, 'Pannier', 33, 54, 'Đã Nẵng', 44);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (84, 'Y-Solowarm', 100, 84, 'Hà Nội', 20);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (85, 'Stim', 21, 60, 'Tp.Hồ Chí Minh', 39);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (86, 'Trippledex', 21, 80, 'Hải Phòng', 45);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (87, 'Bitwolf', 44, 60, 'An Giang', 52);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (88, 'Redhold', 46, 29, 'Cà Mau', 49);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (89, 'Namfix', 50, 75, 'Vũng Tàu', 49);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (90, 'Lotstring', 1, 38, 'Đồng Nai', 20);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (91, 'Aerified', 74, 53, 'Huế', 60);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (92, 'Keylex', 84, 19, 'Đã Nẵng', 32);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (93, 'Overhold', 100, 18, 'Hà Nội', 15);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (94, 'Sonsing', 69, 38, 'Tp.Hồ Chí Minh', 13);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (95, 'Solarbreeze', 25, 29, 'Hải Phòng', 55);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (96, 'Toughjoyfax', 22, 74, 'An Giang', 60);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (97, 'It', 73, 32, 'Cà Mau', 10);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (98, 'Namfix', 44, 55, 'Vũng Tàu', 29);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (99, 'Stringtough', 5, 48, 'Đồng Nai', 26);
insert into product (id, name, newPrice, oldPrice, origin, saleOff) values (100, 'Flexidy', 50, 56, 'Huế', 17);
